train:
  get_spectrogram: # special key for getting spectrogram
    _target_: torchaudio.transforms.MelSpectrogram
    sample_rate: 16000
  audio: # name of the tensor on which we apply transform
    _target_: torchvision.transforms.v2.Compose
    transforms:
      # - _target_: src.transforms.wav_augs.Gain
      - _target_: src.transforms.wav_augs.AddGaussianNoise
        mean: 0.0
        std: 0.001
      - _target_: src.transforms.wav_augs.TimeStretch
        rate: 1.1
inference:
  get_spectrogram:
    _target_: torchaudio.transforms.MelSpectrogram
    sample_rate: 16000
